In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

np.random.seed(42)
pd.set_option('display.max_columns', 60)
pd.set_option('display.width', 180)

Trabajaremos con tres tablas con problemas realistas:
- `customers`: dimensión de clientes
- `products`: dimensión de productos
- `transactions`: tabla de transacciones

La idea es limpiarlas y convertirlas en una tabla analítica única.

### DataFrame Customers
- Total de clientes: 120
- Columnas [customer_id, name, city, segment, age]

In [24]:
# Crear DataFrame Customers
n_customers = 120
customer_ids = np.arange(1000, 1000 + n_customers) # genera un array de números consecutivos (enteros) usando NumPy
names = [f' customer_{i} ' for i in range(n_customers)]
cities = np.random.choice(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'], size=n_customers)
segments = np.random.choice(['Standard', 'Premium'], size=n_customers, p=[0.75, 0.25])
ages = np.random.normal(39, 12, size=n_customers).round().astype(float)

df_customers = pd.DataFrame({
    'customer_id': customer_ids,
    'name':names,
    'city':cities,
    'segment':segments,
    'age':ages
})

# Ensuciar DataFrame Customers
# np.random.choice(df_customers.index, 10, replace=False) Selecciona 10 filas aleatorias, y replace=False evita repetir filas.

# Poner valores Nan en la columna age
df_customers.loc[np.random.choice(df_customers.index, 10, replace=False), 'age'] = np.nan

# Poner valores None en la columna city
df_customers.loc[np.random.choice(df_customers.index, 6, replace=False), 'city'] = None

# Concatenera filas al dataframe
# df_customers.sample(8, random_state=42) selecciona 8 filas aleatorias
# random_state=42 que siempre sean las mismas.
# ignore_index=True reinicia los índices
df_customers = pd.concat([df_customers, df_customers.sample(8, random_state=42)], ignore_index=True)

print("Customers.Shape: ", df_customers.shape)
display("DataFrame Customers", df_customers.head())

Customers.Shape:  (128, 5)

'DataFrame Customers'

   customer_id          name       city   segment   age
0         1000   customer_0     Sevilla  Standard   NaN
1         1001   customer_1      Madrid  Standard  44.0
2         1002   customer_2   Barcelona   Premium  47.0
3         1003   customer_3      Madrid   Premium  52.0
4         1004   customer_4   Barcelona  Standard  30.0

### DataFrame Products
Columnas: 'product_id', 'product_name', 'category', 'base_price'

In [25]:
# Crear DataFrame Products
products_id = np.arange(200, 240)
products_name = [f' Product_{pid} ' for pid in products_id]
categories = np.random.choice(['Electronics', 'Home', 'Sports', 'Books'], size=len(products_id))
base_prices = np.random.uniform(5, 250, size=len(products_id)).round(2)


df_products = pd.DataFrame({
    'product_id':products_id,
    'product_name':products_name,
    'category':categories,
    'base_price':base_prices,
})

# Ensuciar DataFrame Products
df_products.loc[np.random.choice(df_products.index, 5, replace=False), 'category'] = ' electronics '
df_products.loc[np.random.choice(df_products.index, 4, replace=False), 'base_price'] = np.nan
df_products = pd.concat([df_products, df_products.sample(5, random_state=1)], ignore_index=True)

print("Products.Shape: ", df_products.shape)
display("DataFrame Products", df_products.head())

Products.Shape:  (45, 4)

'DataFrame Products'

   product_id   product_name     category  base_price
0         200   Product_200        Sports      216.47
1         201   Product_201   Electronics      148.19
2         202   Product_202        Sports       57.24
3         203   Product_203         Books       27.18
4         204   Product_204          Home      176.40

### DataFrame Transactions:
#### Transactions(Pedidos- un consumidor hace pedido de productos) ---
Columnas: 'tx_id', 'customer_id','product_id','quantity','discount','tx_date'

In [26]:
# Crear DataFrame Transactions(Pedidos)
n_tx = 900
tx_ids = np.arange(5000, 5000 + n_tx)

tx_customer = np.random.choice(df_customers['customer_id'].unique(), size=n_tx)
tx_product = np.random.choice(df_products['product_id'].unique(), size=n_tx)
quantity = np.random.randint(1, 6, size=n_tx)
discount = np.random.choice([0.0, 0.05, 0.10, np.nan], size=n_tx, p=[0.55, 0.2, 0.15, 0.10])

dates = pd.to_datetime('2025-01-01') + pd.to_timedelta(np.random.randint(0, 90, size=n_tx), unit='D')

df_transactions = pd.DataFrame({
    'tx_id': tx_ids,
    'customer_id': tx_customer,
    'product_id': tx_product,
    'quantity': quantity,
    'discount': discount,
    'tx_date': dates,
})

# Ensuciar DataFrame Transaction
df_transactions.loc[np.random.choice(df_transactions.index, 7, replace=False), 'product_id'] = np.nan
transactions = pd.concat([df_transactions, df_transactions.sample(12, random_state=7)], ignore_index=True)

print("Transaction.Shape: ",df_transactions.shape)
display("DataFrame Transaction(Pedidos)", df_transactions.head())

Transaction.Shape:  (900, 6)

'DataFrame Transaction(Pedidos)'

   tx_id  customer_id  product_id  quantity  discount    tx_date
0   5000         1114       217.0         2       0.0 2025-01-24
1   5001         1077       232.0         3       0.0 2025-03-08
2   5002         1071       205.0         1       0.0 2025-02-17
3   5003         1117       224.0         2       0.0 2025-03-06
4   5004         1018       222.0         4       0.0 2025-02-07

### Ejercicio 1
1. Ejecuta `info()` para las tres tablas.
2. Calcula duplicados completos en cada una.
3. Localiza IDs duplicados en `customer_id`, `product_id` y `tx_id`.

In [ ]:
print("******* Info DataFrame Customers *******")
display(df_customers.info())

print("******* Info DataFrame Products *******")
display(df_products.info())

print("******* Info DataFrame Transaction *******")
display(df_transactions.info())

print("Columnas Duplicadas en DF Customers", df_customers.duplicated().sum())
print("Columnas Duplicadas en DF Products", df_products.duplicated().sum())
print("Columnas Duplicadas en DF Transaction", df_transactions.duplicated().sum())

display("Id Duplicadss en DF Customers\n", df_customers[df_customers['customer_id'].duplicated(keep=False)])
display("Id Duplicadss en DF Products\n", df_products[df_products['product_id'].duplicated(keep=False)])
display("Id Duplicadss en DF Transaction\n", df_transactions[df_transactions['tx_id'].duplicated(keep=False)])

******* Info DataFrame Customers *******
******* Info DataFrame Products *******
******* Info DataFrame Transaction *******

'Id Duplicadss en DF Customers\n'

     customer_id           name       city   segment   age
4           1004    customer_4   Barcelona  Standard  30.0
10          1010   customer_10     Sevilla  Standard  22.0
26          1026   customer_26    Valencia  Standard  34.0
44          1044   customer_44         NaN  Standard  27.0
47          1047   customer_47   Barcelona  Standard  35.0
55          1055   customer_55      Madrid  Standard  43.0
64          1064   customer_64     Sevilla  Standard  54.0
73          1073   customer_73    Valencia  Standard  32.0
120         1044   customer_44         NaN  Standard  27.0
121         1047   customer_47   Barcelona  Standard  35.0
122         1004    customer_4   Barcelona  Standard  30.0
123         1055   customer_55      Madrid  Standard  43.0
124         1026   customer_26    Valencia  Standard  34.0
125         1064   customer_64     Sevilla  Standard  54.0
126         1073   customer_73    Valencia  Standard  32.0
127         1010   customer_10     Sevilla  Standard  22.0

'Id Duplicadss en DF Products\n'

    product_id   product_name category  base_price
2          202   Product_202    Sports       57.24
3          203   Product_203     Books       27.18
21         221   Product_221    Sports      171.19
27         227   Product_227      Home      163.64
31         231   Product_231    Sports      200.83
40         202   Product_202    Sports       57.24
41         231   Product_231    Sports      200.83
42         203   Product_203     Books       27.18
43         221   Product_221    Sports      171.19
44         227   Product_227      Home      163.64

'Id Duplicadss en DF Transaction\n'

Empty DataFrame
Columns: [tx_id, customer_id, product_id, quantity, discount, tx_date]
Index: []